<?php

namespace Database\Seeders;

use App\Models\Mascota;
use App\Models\Cliente;
use App\Models\Raza;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MascotaSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Mascota::truncate();
        Schema::enableForeignKeyConstraints();

        $clientesIds = Cliente::pluck('id')->toArray();
        $razasIds = Raza::pluck('id')->toArray();

        if (empty($clientesIds) || empty($razasIds)) {
            return;
        }

        $nombres = [
            'Luna','Thor','Coco','Max','Bella','Toby','Simba','Milo','Lola','Rocky',
            'Kira','Pancho','Bimba','Bruno','Zeus','Maya','Nala','Lucas','Pipo','Daisy',
            'Rocco','Chispa','Blanquita','Blacky','Gala','Bethoven','Odin','Frida','Sasha','Paco',
            'Blue','Rex','Minnie','Goku','Kiara','Boby','Canela','Cookie','Dante','Duke',
            'Hulk','Jack','Kenai','Kyra','Layla','Lucky','Mia','Nemo','Otto','Pepe',
            'Chester','Apolo','Bolt','Balu','Koda','Loki','Hera','Athena','Ares','Nova',
            'Runa','Zara','Nina','Tina','Pinky','Tobyas','Bongo','Simón','Teo','Rufi',
            'Chiqui','Firu','Manchas','Pelusa','Bigotes','Copito','Nieve','Sol','Sombra','Trueno',
            'Relámpago','Fuego','Ámbar','Canelo','Moka','Capuchino','Latte','Brownie','Choco','Caramelo',
            'Fresa','Vainilla','Menta','Nube','Cielo','Estrella','Cometa','Cosmo','Astro','Pixel','Bambi','Benji',
            'Balto','Baxter','Boomer','Boris','Buster','Charly','Chato','Choco',
            'Churro','Ciro','Clifford','Colmillo','Copérnico','Cruz','Danko','Dobby','Draco','Duque',
            'Eco','Eliot','Elvis','Enzo','Eros','Fido','Flash','Fox','Frodo','Gandalf',
            'Gaspar','Gizmo','Goliat','Greco','Guapo','Hachi','Hades','Haru','Horus','Indy',
            'Iris','Jagger','Juno','Kaiser','Kano','Kasper','Kenzo','Khal','Kovu','Kratos',
            'Lenny','León','Link','Logan','Lorenzo','Maddox','Mambo','Maní','Marley','Maverick',
            'Merlín','Messi','Moana','Mowgli','Nacho','Neo','Nico','Niko','Nina','Nube',
            'Olaf','Onix','Orion','Panda','Pantera','Paris','Pelón','Picasso','Pikachu','Pingo',
            'Pluto','Poncho','Pongo','Prince','Pumba','Quincy','Ragnar','Rambo','Rayo','Remy','Atila','Atlas',
            'Baco','Bandit','Barney','Bingo','Blaze','Blitz','Brandy','Bronco',
            'Bruce','Cairo','Canelo','Capo','Caspian','César','Chesterfield','Chimuelo','Cholo','Ciclón',
            'Cococho','Coloso','Comino','Congo','Cosito','Coyote','Dakar','Dálmata','Dango','Dardo',
            'Demon','Denver','Dingo','Domino','Donatello','Drake','Edison','Electra','Elmo','Eminem',
            'Faraón','Félix','Fénix','Fito','Floki','Fluffy','Forrest','Furia','Galileo','Garra',
            'Gordo','Groot','Gucci','Gus','Hércules','Hielo','Hipo','Hoshi','Igor','Indiana',
            'Jade','Jasper','Jazz','Júpiter','Kali','Karma','Kendo','Khan','Kiko','Kira','Kobe',
            'Koda','Krypto','Lara','Lasso','Lázaro','Lego','Levi','Lince','Lobo','Lucho','Limon','Mango','Fresa','Guayabo','Chorizo',
            'Mamba','Mango','Maximus','Memphis','Merlot','Midas','Mimo','Minos','Mishka',
            'Místico','Abby','Aiko','Akira','Alfa','Alvin','Amber','Anubis','Arlo','Arwen','Aslan',
            'Aura','Axel','Balú','Basil','Beast','Bela','Benny','Beryl','Bianca','Bolt',
            'Bongo','Bowie','Bree','Brock','Brook','Cali','Cami','Candy','Capi','Capri',
            'Carlo','Cata','Cleo','Clover','Cody','Cora','Coral','Dalia','Delta','Dina',
            'Diva','Dixie','Duna','Echo','Eira','Elka','Elsa','Ema','Ember','Enya',
            'Era','Esme','Fany','Fara','Fiona','Flora','Gaia','Gala','Gemma','Gina',
            'Ginger','Giselle','Greta','Hana','Heidi','Holly','Honey','India','Indra','Ivy',
            'Jade','Jana','Jazzy','Jelly','Jinx','Jojo','Kali','Katy','Kena','Kika',
            'Kira','Koko','Kylo','Lana','Laska','Leia','Lila','Lili','Lina','Lira'
];

        $sexos = ['macho', 'hembra'];
        $descripciones = [
            'Mascota muy sana, activa y con excelente estado físico general, ideal para convivir con familias.',
            'Muy dócil y obediente, responde bien a órdenes básicas y es fácil de entrenar.',
            'Energética y juguetona, le encanta correr, saltar y mantenerse en constante movimiento.',
            'Tranquila y relajada, perfecta para espacios pequeños o personas que buscan compañía calmada.',
            'Veterana pero en buen estado de salud, con carácter noble y comportamiento equilibrado.',
            'Atleta natural, disfruta actividades al aire libre y tiene gran resistencia física.',
            'Muy cariñosa, busca constantemente afecto y compañía de sus dueños.',
            'Independiente pero sociable, puede adaptarse bien a estar sola por periodos cortos.',
            'Amigable con otros animales, convive sin problemas con perros o gatos.',
            'Le encanta jugar con niños, tiene un carácter paciente y protector.',
            'De tamaño pequeño, ideal para departamentos o espacios reducidos.',
            'De tamaño mediano, equilibrada entre energía y manejo sencillo.',
            'De tamaño grande, fuerte y protectora, requiere espacio amplio.',
            'Buen apetito y hábitos alimenticios estables, no presenta problemas digestivos.',
            'Pelaje suave y brillante, requiere cuidados básicos de higiene.',
            'Fácil de bañar y cepillar, tolera bien la rutina de limpieza.',
            'Muy inteligente, aprende rápidamente nuevos comandos y rutinas.',
            'Curiosa por naturaleza, explora constantemente su entorno.',
            'Le gusta dormir largas horas, especialmente en ambientes tranquilos.',
            'Activa durante el día, mantiene horarios de juego constantes.',
            'Protectora con su familia, alerta ante extraños.',
            'No presenta problemas de agresividad, comportamiento equilibrado.',
            'Se adapta fácilmente a nuevos entornos y cambios de rutina.',
            'Disfruta paseos diarios y actividades al aire libre.',
            'Buen comportamiento en casa, no destructiva.',
            'Puede convivir en espacios compartidos sin inconvenientes.',
            'Requiere ejercicio moderado para mantenerse saludable.',
            'No presenta alergias conocidas ni condiciones médicas relevantes.',
            'Ideal como mascota de compañía para personas mayores.',
            'Leal y fiel, genera vínculos fuertes con sus dueños.',
            'Buen comportamiento en visitas al veterinario.',
            'Tolerante a ruidos y ambientes concurridos.',
            'Se lleva bien con visitas y personas desconocidas.',
            'No suele ladrar en exceso, comportamiento tranquilo.',
            'Nivel de energía balanceado, ni muy activo ni muy pasivo.',
            'Pelaje corto de fácil mantenimiento.',
            'Pelaje largo que requiere cepillado frecuente.',
            'Se adapta bien a climas cálidos.',
            'Se adapta bien a climas fríos.',
            'No presenta ansiedad por separación.',
            'Puede quedarse sola por algunas horas sin problema.',
            'Le gusta jugar con juguetes y objetos interactivos.',
            'Buena coordinación y agilidad física.',
            'Carácter amigable y confiable.',
            'No presenta conductas destructivas.',
            'Ideal para familias con experiencia en mascotas.',
            'Puede aprender trucos avanzados con entrenamiento constante.',
            'Se mantiene alerta pero sin ser agresiva.',
            'Buen estado general y revisiones veterinarias al día.',
            'Mascota equilibrada, saludable y con excelente comportamiento general.',
            'Mascota sociable y amigable, disfruta la compañía tanto de personas como de otros animales.',
            'De carácter tranquilo, ideal para hogares con ambiente relajado y sin mucho ruido.',
            'Muy activa durante paseos, le encanta explorar y descubrir nuevos lugares.',
            'Presenta buen estado de salud general, con vacunas y desparasitaciones al día.',
            'Le gusta recibir atención constante, busca cariño y contacto físico frecuente.',
            'Se adapta bien a rutinas establecidas, responde positivamente a horarios fijos.',
            'Buen comportamiento en interiores, no causa daños ni desorden en el hogar.',
            'Nivel de energía moderado, combina momentos de juego con largos periodos de descanso.',
            'Se muestra alerta pero sin signos de agresividad, adecuada como mascota familiar.',
            'Disfruta interactuar con juguetes, especialmente aquellos que estimulan su mente.',
            'Puede convivir con otras mascotas si se introduce de manera adecuada.',
            'De carácter curioso, le gusta investigar su entorno y mantenerse activa.',
            'Responde bien al entrenamiento básico, aprende con facilidad.',
            'Le gusta descansar en espacios cómodos y tranquilos dentro del hogar.',
            'No presenta problemas de comportamiento, mantiene actitud estable.',
            'Se siente cómoda en presencia de niños, mostrando paciencia y tolerancia.',
            'Ideal para personas que buscan una mascota equilibrada y manejable.',
            'Buena condición física, apta para actividades recreativas moderadas.',
            'No requiere cuidados especiales más allá de los básicos.',
            'Se adapta tanto a espacios grandes como medianos sin inconvenientes.',
            'Tiende a formar vínculos fuertes con su dueño principal.',
            'Comportamiento predecible y fácil de manejar en diferentes situaciones.',
            'No presenta signos de estrés ante cambios leves en su entorno.',
            'Disfruta la compañía humana y se muestra receptiva al contacto.',
            'Puede mantenerse entretenida por sí sola durante periodos cortos.',
            'Pelaje en buenas condiciones, sin signos de problemas dermatológicos.',
            'Se muestra receptiva a la socialización con nuevas personas.',
            'No presenta conductas territoriales marcadas.',
            'Capaz de adaptarse a distintos estilos de vida.',
            'Requiere paseos diarios para mantener su equilibrio físico y mental.',
            'Se muestra relajada en ambientes controlados.',
            'Buen temperamento, adecuado para convivencia diaria.',
            'No presenta hábitos destructivos dentro del hogar.',
            'Le gusta la interacción constante, pero también respeta espacios.',
            'Se adapta bien a cambios de rutina si se hacen de forma gradual.',
            'Comportamiento dócil y fácil de manejar en diferentes entornos.',
            'Disfruta momentos de juego pero también de descanso prolongado.',
            'Buena relación con su entorno, sin signos de ansiedad.',
            'Puede convivir con otras mascotas bajo supervisión inicial.',
            'Se mantiene activa sin llegar a ser hiperactiva.',
            'Carácter equilibrado, ideal para familias.',
            'No presenta problemas digestivos ni de alimentación.',
            'Se muestra confiada en ambientes conocidos.',
            'Responde bien a estímulos positivos durante el entrenamiento.',
            'Puede adaptarse a vivir en interiores sin problemas.',
            'Disfruta de la compañía pero no depende completamente de ella.',
            'Se comporta adecuadamente en visitas al veterinario.',
            'No presenta miedos excesivos ante ruidos comunes.',
            'Buen estado emocional y físico general.',
            'Mascota estable, confiable y de fácil convivencia.',
            'Mascota activa con buen estado físico, disfruta actividades al aire libre y paseos frecuentes.',
            'De temperamento noble, se adapta fácilmente a distintos tipos de familia.',
            'Le gusta explorar su entorno, mostrando curiosidad constante sin ser destructiva.',
            'Buen comportamiento en casa, mantiene hábitos limpios y ordenados.',
            'Se muestra tranquila en interiores, pero activa cuando se le estimula.',
            'Disfruta la compañía de humanos y busca interacción de forma constante.',
            'No presenta problemas de socialización con otras mascotas.',
            'Responde adecuadamente a comandos básicos y rutinas diarias.',
            'Le agrada descansar en lugares cómodos y seguros dentro del hogar.',
            'Nivel de energía medio, ideal para convivencia equilibrada.',
            'Se muestra confiada en ambientes conocidos y segura de sí misma.',
            'No presenta signos de agresividad ni conductas problemáticas.',
            'Le gusta jugar con objetos y mantenerse entretenida por largos periodos.',
            'Puede convivir en espacios reducidos si recibe ejercicio diario.',
            'Carácter amigable, ideal para hogares con visitas frecuentes.',
            'Se adapta a cambios moderados sin mostrar estrés significativo.',
            'Disfruta de la rutina diaria y responde bien a la disciplina.',
            'Buen estado de salud general, sin antecedentes relevantes.',
            'Se muestra atenta a su entorno, sin ser excesivamente nerviosa.',
            'Le gusta interactuar con otros animales de manera pacífica.',
            'Puede permanecer sola por periodos cortos sin ansiedad.',
            'Pelaje en buen estado, requiere cuidados básicos de higiene.',
            'Se comporta de forma adecuada en situaciones nuevas.',
            'Disfruta paseos tranquilos y momentos de relajación.',
            'Se muestra receptiva al entrenamiento con refuerzo positivo.',
            'No presenta hábitos destructivos ni conductas indeseadas.',
            'Carácter equilibrado, ideal para convivencia en familia.',
            'Se adapta bien a la vida en interiores y exteriores.',
            'Le gusta recibir atención pero también respeta espacios.',
            'Se mantiene activa sin ser hiperactiva.',
            'Buen temperamento, confiable en distintos entornos.',
            'No presenta problemas de alimentación ni digestión.',
            'Se muestra relajada en presencia de su dueño.',
            'Disfruta el contacto físico y las caricias.',
            'Puede convivir con niños bajo supervisión adecuada.',
            'Se adapta a diferentes estilos de vida sin dificultad.',
            'No presenta ansiedad ante ruidos comunes.',
            'Le gusta jugar de forma moderada y controlada.',
            'Se mantiene alerta sin mostrar agresividad.',
            'Buen comportamiento general en el hogar.',
            'Se muestra tranquila durante el descanso.',
            'Disfruta de espacios abiertos y ventilados.',
            'No presenta conductas territoriales marcadas.',
            'Se adapta bien a nuevas rutinas si se introducen gradualmente.',
            'Carácter dócil y fácil de manejar.',
            'Se mantiene en buen estado físico con ejercicio regular.',
            'No presenta signos de estrés constante.',
            'Se comporta adecuadamente en consultas veterinarias.',
            'Buen equilibrio entre actividad y descanso.',
            'Mascota estable, saludable y de convivencia sencilla.',
            'Mascota con carácter amigable, disfruta la convivencia diaria y el contacto cercano.',
            'Se muestra activa durante el día, pero sabe relajarse en momentos de descanso.',
            'Buen comportamiento general, adecuada para hogares tranquilos.',
            'Le gusta participar en actividades al aire libre y paseos cortos.',
            'No presenta dificultades para adaptarse a nuevos entornos.',
            'Carácter equilibrado, sin cambios bruscos de comportamiento.',
            'Disfruta de la compañía humana sin volverse dependiente.',
            'Se mantiene tranquila en interiores y activa en exteriores.',
            'Buena respuesta a rutinas establecidas y horarios definidos.',
            'No presenta problemas de convivencia con otros animales.',
            'Le gusta explorar su entorno de forma calmada.',
            'Se muestra confiada en espacios conocidos.',
            'Buen estado de salud y condición física general.',
            'Puede convivir con niños bajo supervisión responsable.',
            'Disfruta momentos de juego moderado.',
            'No presenta conductas destructivas en el hogar.',
            'Se adapta bien a la vida doméstica.',
            'Le agrada descansar en lugares cómodos y seguros.',
            'Responde positivamente al entrenamiento básico.',
            'Se muestra alerta sin ser agresiva.',
            'Carácter dócil, fácil de manejar en distintas situaciones.',
            'No presenta ansiedad ante cambios leves en la rutina.',
            'Se mantiene activa sin ser inquieta en exceso.',
            'Buen temperamento para convivencia diaria.',
            'Disfruta del contacto físico y la atención moderada.',
            'Puede pasar tiempo sola sin mostrar estrés.',
            'Se adapta a espacios medianos o reducidos.',
            'No presenta problemas de comportamiento notorios.',
            'Le gusta interactuar de forma tranquila con su entorno.',
            'Se mantiene relajada en presencia de su dueño.',
            'Buen equilibrio entre actividad y descanso.',
            'No presenta reacciones exageradas ante estímulos comunes.',
            'Se comporta adecuadamente en visitas externas.',
            'Disfruta de ambientes calmados y organizados.',
            'Se adapta bien a nuevas rutinas si se introducen gradualmente.',
            'No presenta signos de agresividad ni miedo excesivo.',
            'Le gusta jugar de manera controlada.',
            'Carácter estable y confiable.',
            'Se mantiene en buen estado físico con cuidados básicos.',
            'No requiere atención especializada.',
            'Se muestra receptiva a nuevas experiencias.',
            'Puede convivir con otras mascotas sin inconvenientes.',
            'Disfruta tanto la actividad como el descanso.',
            'Se comporta adecuadamente en interiores.',
            'No presenta hábitos negativos dentro del hogar.',
            'Le gusta la interacción social moderada.',
            'Se mantiene tranquila en ambientes conocidos.',
            'Buen comportamiento general en diferentes situaciones.',
            'Carácter adaptable a distintos estilos de vida.',
            'Mascota fácil de cuidar y mantener.',
            'No presenta hábitos destructivos.',
            'Le gusta la compañía pero también valora su espacio.',
            'Se adapta a diferentes ritmos de vida.',
            'Buen temperamento en general.',
            'Se mantiene estable emocionalmente.',
            'Disfruta paseos tranquilos y sin prisa.',
        ];
        for ($i = 0; $i < 450; $i++) {
            $fechaRegistro = now()->subDays(rand(0, 180))->subMinutes(rand(0, 1440));
            /*entre 0 y 375 para nombres random

            entre 0 y 205 descripcions
            $nombreFinal = isset($nombres[$i]) ? $nombres[$i] : 'Mascota ' . ($i + 1);*/

            Mascota::create([
                'nombre' => $nombres[array_rand($nombres)],
                'sexo' => $sexos[array_rand($sexos)],
                'peso' => rand(1, 40) + (rand(0, 99) / 100),
                'descripcion' => $descripciones[array_rand($descripciones)],
                'fecha_nacimiento' => now()->subYears(rand(1, 12))->subMonths(rand(0, 11))->toDateString(),
                'cliente_id' => $clientesIds[array_rand($clientesIds)],
                'raza_id' => $razasIds[array_rand($razasIds)],
                'visibilidad' => 'visible',
                'created_at' => $fechaRegistro,
                'updated_at' => $fechaRegistro
            ]);
        }
        
        $this->command->info("¡Se crearon 150 mascotas exitosamente!");
    }
}